// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAupeodleBCU57A6HnvGpTajDEc8BKtt0',
    appId: '1:1056428983613:web:b6d1608a4fe7c43cfbb154',
    messagingSenderId: '1056428983613',
    projectId: 'stepquest-40955',
    authDomain: 'stepquest-40955.firebaseapp.com',
    storageBucket: 'stepquest-40955.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhoXA5-V1HzHynWVz2DI-ERY4LLnPDpG0',
    appId: '1:1056428983613:android:94bfd1fc52370ca9fbb154',
    messagingSenderId: '1056428983613',
    projectId: 'stepquest-40955',
    storageBucket: 'stepquest-40955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA7a6kCAIJBw3FPgblYgkPOPaDC9G0zvw',
    appId: '1:1056428983613:ios:7d82bc5adb61b688fbb154',
    messagingSenderId: '1056428983613',
    projectId: 'stepquest-40955',
    storageBucket: 'stepquest-40955.firebasestorage.app',
    iosBundleId: 'com.example.stepQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA7a6kCAIJBw3FPgblYgkPOPaDC9G0zvw',
    appId: '1:1056428983613:ios:7d82bc5adb61b688fbb154',
    messagingSenderId: '1056428983613',
    projectId: 'stepquest-40955',
    storageBucket: 'stepquest-40955.firebasestorage.app',
    iosBundleId: 'com.example.stepQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAupeodleBCU57A6HnvGpTajDEc8BKtt0',
    appId: '1:1056428983613:web:6c4b0aac120102bcfbb154',
    messagingSenderId: '1056428983613',
    projectId: 'stepquest-40955',
    authDomain: 'stepquest-40955.firebaseapp.com',
    storageBucket: 'stepquest-40955.firebasestorage.app',
  );

}